import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/features/auth/UserProvider";
import { ApolloWrapper } from "@/features/auth/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <ApolloWrapper>
        <UserProvider>
          <body className={inter.className}>
            <header>ヘッダー</header>
            {children}
            <footer>フッター</footer>
          </body>
        </UserProvider>
      </ApolloWrapper>
    </html>
  );
}
